name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Rodar testes de API (Playwright)
      run: npx playwright test tests/api/

    - name: Rodar testes E2E + Mobile (Appium)
      run: npx wdio run wdio.conf.js

    - name: Gerar relatório Allure (opcional)
      if: always()
      run: |
        npm install -g allure-commandline
        allure generate allure-results --clean -o allure-report
        echo "Relatório gerado em allure-report/"
